DROP TABLE if EXISTS SECTIONS_PRODUCTS;
DROP TABLE if EXISTS SECTIONS;
DROP TABLE if EXISTS WAREHOUSES;
DROP TABLE if EXISTS PRODUCTS;
DROP TABLE if EXISTS USERS;


CREATE TABLE USERS(
    id SERIAL PRIMARY KEY,
    username VARCHAR(40) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCTS(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sku VARCHAR(10) NOT NULL,
    product_type VARCHAR(40) NOT NULL CHECK(product_type IN ('STRING', 'BRASS', 'PERCUSSION', 'OTHER')),
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE WAREHOUSES(
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL DEFAULT 'Untitled',
    warehouse_type VARCHAR(40) NOT NULL CHECK(warehouse_type IN ('INSTRUMENTS')),
    capacity INTEGER DEFAULT 0,
    location VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SECTIONS(
    id SERIAL PRIMARY KEY,
    warehouse_id INTEGER REFERENCES WAREHOUSES(id) ON DELETE CASCADE,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SECTIONS_PRODUCTS(
    section_id INTEGER REFERENCES SECTIONS(id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES PRODUCTS(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (section_id, product_id)
)



